# Generated by Django 3.1.4 on 2020-12-28 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubPackage',
            fields=[
                ('sub_package_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_package_name', models.CharField(max_length=255)),
                ('component', models.CharField(max_length=255)),
                ('master_package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecm.masterpackage')),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecm.package')),
            ],
        ),
    ]
