# Generated by Django 3.1.4 on 2020-12-28 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecm', '0002_subpackage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubPackage',
            new_name='Version',
        ),
        migrations.RenameField(
            model_name='version',
            old_name='sub_package_id',
            new_name='version_id',
        ),
        migrations.RenameField(
            model_name='version',
            old_name='sub_package_name',
            new_name='version_name',
        ),
    ]
